In [1]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/4. Linear Transforms/7. Gramm Matrix")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [1]:
import numpy as np

def contra_to_co(B, x):
   
    G = np.dot(B.T, B)
    
    x_dot_B = np.dot(B.T, x)
    x_covariant = np.linalg.solve(G, x_dot_B)
    
    return x_covariant




In [3]:
import time

start = time.time()

debug_result = [contra_to_co(**x) for x in debug_cases]
answer = [contra_to_co(**x) for x in public_cases]

print(time.time() - start, '<- Elapsed time')

[[  1  -2  -4   2  -2  -4   0]
 [ -1   3   2  -2  -2   8  -4]
 [ -4  10  13  -7   3  26  -9]
 [  0   3 -11  -4 -24   5 -12]
 [  3  -9  -7   2  -5 -33  30]
 [  1  -6   2   3  13 -22  -6]
 [  4  -9 -18   2 -21 -30  19]]
[-4 -5  1  1  2 -1 -3]
[[  1   2  -5  -5  -4  -4   0   1]
 [  1   3 -10  -8  -8  -5   4   1]
 [ -2  -6  21  18  11  10  -6  -3]
 [  0  -4  24  21  -9   7  -8  -7]
 [  1   5 -19 -17   5 -25  12  16]
 [  3   3   1  -4  -3 -14 -12  -1]
 [ -3  -2  -3   7 -12   5  23 -14]
 [ -5  -6   3  10   5  28   9 -14]]
[ 3  3 -3 -3 -3 -2  2  0]
[[  1   3   4   0   4  -3   2   2]
 [ -3  -8 -11  -4  -8   5  -2 -11]
 [ -3  -6  -8 -12   1   1   7 -17]
 [  2   8  11  -7  21  -9  16  -4]
 [  1   3   4   0   5  -7  -2   3]
 [ -1  -8 -14  19 -36  15 -14   2]
 [ -5 -16 -21   1 -33   3 -38   6]
 [ -1  -6 -12  10 -30  -2 -22 -13]]
[ 2 -2 -4  4 -3 -5  2 -3]
[[  1  -1  -2   2   1  -4  -5]
 [  4  -3 -12   5  -1 -21 -23]
 [ -5   6   7 -18  -8  19  18]
 [ -3   2  10  -2  -3  21  20]
 [ -1   5 -10 -35  -7