In [2]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/3. Matrices/13. LL product")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [5]:
import numpy as np

def LL_product(L1, L2):
    
    n = len(L1)
    C = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            C[i][j] = sum(L1[i][k] * L2[k][j] for k in range(j + 1))
    
    print(C)
    return C

In [6]:
import time

start = time.time()

debug_result = [LL_product(**x) for x in debug_cases]
answer = [LL_product(**x) for x in public_cases]

print(time.time() - start, '<- Elapsed time')

[[-10.   0.   0.   0.   0.   0.   0.]
 [  5.  -8.   0.   0.   0.   0.   0.]
 [ 20.   8.   0.   0.   0.   0.   0.]
 [  0.  12. -10.  16.   0.   0.   0.]
 [-15. -12.  -2. -12.  -5.   0.   0.]
 [ -5. -16.  -4.  12.  20. -20.   0.]
 [-20.  -4.  -8.  -8.  -5. -10.  -6.]]
[[-3.  0.]
 [-6.  3.]]
[[3.]]
[[4.]]
[[-16.   0.   0.   0.   0.   0.   0.]
 [  4.  -4.   0.   0.   0.   0.   0.]
 [ 16. -16. -12.   0.   0.   0.   0.]
 [ -4. -12.  -4.  25.   0.   0.   0.]
 [  8. -12.  12.  -5.   0.   0.   0.]
 [  4.  20.  12. -20. -10.   0.   0.]
 [-12.   8.  20.  25. -20.   6.   1.]]
[[-5.  0.]
 [ 3. -4.]]
[[-15.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ -9.  12.   0.   0.   0.   0.   0.   0.   0.]
 [-15.  -8.  -8.   0.   0.   0.   0.   0.   0.]
 [  9.  16. -16.   8.   0.   0.   0.   0.   0.]
 [ -6.  20.  -4.   4.  -6.   0.   0.   0.   0.]
 [-15.  12.   0.  -2.   0.   0.   0.   0.   0.]
 [  6.  16.  -4.  10.  15.   0.   6.   0.   0.]
 [-15.  20.  -4.   0.   9.   0.   2.  -6.   0.]
 [ -3.  12. -20.   4. 