In [1]:
%reload_ext autoreload
%autoreload 2

import sys
import os
from pathlib import Path
import json_tricks

path = Path('.').resolve()

index = str(path).find('.laborantum')

if index > 0:
    path = str(path)[:index]

os.chdir(path)

path = Path(".laborantum/texts/Homeworks/3. Matrices/14. Diagonal Matrices Product")

debug_cases = json_tricks.load(
    str(path / 'testcases' / 'debug_cases.json'))
public_cases = json_tricks.load(
    str(path / 'testcases' / 'public_cases.json'))

In [6]:
import numpy as np

def DA_AD_product(D, A):

    res = {
        'DA': 0,
        'AD': 0
    }
    
    return res

In [7]:
import time

start = time.time()

debug_result = [DA_AD_product(**x) for x in debug_cases]
answer = [DA_AD_product(**x) for x in public_cases]

print(time.time() - start, '<- Elapsed time')

[[-5 -2 -4  2 -2 -4  0]
 [ 0  4 -2  0 -4  4 -4]
 [ 4 -2  2  1  3  2 -1]
 [-4 -1  2  4  3  3 -5]
 [ 3  1  3  2 -5  2  2]
 [-3 -5  2 -3 -3 -5 -1]
 [ 4  1  4  3  1  3  2]]
{'DA': array([[[-10,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  8,   0,   0,   0,   0,   0,   0],
        [ -8,   0,   0,   0,   0,   0,   0],
        [  6,   0,   0,   0,   0,   0,   0],
        [ -6,   0,   0,   0,   0,   0,   0],
        [  8,   0,   0,   0,   0,   0,   0]],

       [[  0,   4,   0,   0,   0,   0,   0],
        [  0,  -8,   0,   0,   0,   0,   0],
        [  0,   4,   0,   0,   0,   0,   0],
        [  0,   2,   0,   0,   0,   0,   0],
        [  0,  -2,   0,   0,   0,   0,   0],
        [  0,  10,   0,   0,   0,   0,   0],
        [  0,  -2,   0,   0,   0,   0,   0]],

       [[  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0],
        [ 